version: "3"
services:
  mf-ecommerce-host:
    image: "xyzuan/mf-ecommerce-host:1.1"
    container_name: fe-ecommerce-host
    ports:
      - "4250:4250"
  mf-list-product:
    image: "xyzuan/mf-list-product:1.1"
    container_name: mf-list-product
    ports:
      - "4251:4251"
  mf-payment-and-cart:
    image: "xyzuan/mf-payment-and-cart:1.1"
    container_name: mf-payment-and-cart
    ports:
      - "4252:4252"
  db:
    image: "postgres:14.5-alpine"
    restart: always
    container_name: ecommerce-db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=ecommerce123
    ports:
      - "41120:5432"
    volumes:
      - /home/xyzuan/work/len/ecommerce_db:/var/lib/postgresql/data
